## .travis.yml

language: Swift
xcode_workspace: PoietData.xcworkspace # path to your xcodeproj folder
xcode_scheme: PoietData
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11
SWIFT_VERSION: 5.0